import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import os
# Files and locations
userloc = os.getcwd()

data_post = userloc+'/data2025post/' # post-processing, generated by our scripts
rated = pd.read_parquet(data_post + 'rated_notes_compact.parquet', engine='auto')


# Restricting our analysis to notes after 2024
rated_2024 = rated[(rated.createdAt >= pd.Timestamp(2024, 1, 1))]

# Find the first note written by each author, and if that author goes on to write another note
first_notes = rated.groupby('noteAuthorParticipantId')\
    [['createdAt', 'finalRatingStatus', 'numRatings', 'decidedBy','coreNoteIntercept', 'coreNoteInterceptMax', 'expansionNoteIntercept', 'expansionNoteInterceptMax', 'classification']]\
    .first().reset_index()
# Restricting our analysis to authors who joined in 2024 
first_notes = first_notes[(first_notes.createdAt >= pd.Timestamp(2024, 1, 1)) &
                          (first_notes.createdAt < pd.Timestamp(2025, 1, 1))]
have_another_note = rated_2024[rated_2024.groupby('noteAuthorParticipantId').cumcount() >= 2]\
    ['noteAuthorParticipantId'].to_list()
first_notes['if_written_again'] = first_notes['noteAuthorParticipantId'].isin(have_another_note)
# notes are scored by multiuple algorithms, but nearly 80% are scored by the core model
# TODO for now restrict our analysis to this model
first_notes = first_notes[first_notes['decidedBy'].isin(['CoreModel (v1.1)'])]
# remove NNNs
first_notes = first_notes[first_notes['classification'] != 'NOT_MISLEADING']

cutoff = .4
bandwidth = float(input("Enter the bandwidth: "))


# only aligned notes with max score
running_variable_max = np.where(
    first_notes["decidedBy"] == "CoreModel (v1.1)",
    first_notes["coreNoteInterceptMax"],
    first_notes["expansionNoteInterceptMax"]
) # x value, continuous input

first_notes['intercept'] = running_variable_max
# keep when intercept and locked status align
# Treatment = 1 if running_variable >= cutoff, else 0
treatment = np.where(running_variable_max >= cutoff, 1, 0)
outcome_variable = first_notes['if_written_again'].astype(int)

mask_alignment = (((first_notes["intercept"] > cutoff) & (first_notes["finalRatingStatus"] == "CURRENTLY_RATED_HELPFUL")) |
    ((first_notes["intercept"] < cutoff) & (first_notes["finalRatingStatus"] != "CURRENTLY_RATED_HELPFUL")))
mask = (running_variable_max > cutoff - bandwidth)  & (running_variable_max < cutoff + bandwidth)
data = pd.DataFrame({
    'running_variable': running_variable_max[mask & mask_alignment],
    'treatment': treatment[mask & mask_alignment],
    'outcome_variable': outcome_variable[mask & mask_alignment]
})

# Center the running variable at the cutoff for easier interpretation of the intercept
data['running_variable_centered'] = data['running_variable'] - cutoff
print(f"\nAligned data, max score")
print(f"\nNumber of treated units: {data['treatment'].sum()}")
print(f"Number of control units: {data['treatment'].count() - data['treatment'].sum()}")
# original
rdd_model_formula = 'outcome_variable ~ running_variable_centered * treatment'

rdd_model = smf.ols(formula=rdd_model_formula, data=data).fit()
# The coefficient for 'treatment' is the estimated effect at the cutoff.
estimated_effect = rdd_model.params['treatment']
print(f"\nEstimated Treatment Effect at the Cutoff: {estimated_effect:.4f}")

print("I think we can intepret this as a % change the chance of authoring again if published")

p_value_treatment = rdd_model.pvalues['treatment']
t_statistic_treatment = rdd_model.tvalues['treatment']

# print out p value and t-statistic for treatment
print(f"\nP-value for treatment: {p_value_treatment:.4f}")
print(f"T-statistic for treatment: {t_statistic_treatment:.4f}")
